export 'home_page.dart';
export 'medic_page.dart';
export 'kontrol_page.dart';
export 'kesehatan_page.dart';
export 'konsultasi_page.dart';
export 'register_page.dart';
export 'profile_page.dart';
export 'login_page.dart';
export 'setting_page.dart';
