// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2rryf04IzVmdnnwMUnFueBm8lv3RiV1k',
    appId: '1:25984849347:web:2801e9f55df1fd483d9976',
    messagingSenderId: '25984849347',
    projectId: 'sistem-gereja-terpadu',
    authDomain: 'sistem-gereja-terpadu.firebaseapp.com',
    storageBucket: 'sistem-gereja-terpadu.appspot.com',
    measurementId: 'G-3TCZ568JJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoMdtmOi_EO21CnsYOI2JG87-AjJrtfrw',
    appId: '1:25984849347:android:cf334d70718c8c733d9976',
    messagingSenderId: '25984849347',
    projectId: 'sistem-gereja-terpadu',
    storageBucket: 'sistem-gereja-terpadu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOc71wFz_o1_ozqGgZHt3J-VJCeOYnLS8',
    appId: '1:25984849347:ios:be27de2d0ad10cbf3d9976',
    messagingSenderId: '25984849347',
    projectId: 'sistem-gereja-terpadu',
    storageBucket: 'sistem-gereja-terpadu.appspot.com',
    iosClientId:
        '25984849347-dk7vrm230a11f81gmvos3ti1evvk8jnv.apps.googleusercontent.com',
    iosBundleId: 'com.example.neoSgtUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOc71wFz_o1_ozqGgZHt3J-VJCeOYnLS8',
    appId: '1:25984849347:ios:be27de2d0ad10cbf3d9976',
    messagingSenderId: '25984849347',
    projectId: 'sistem-gereja-terpadu',
    storageBucket: 'sistem-gereja-terpadu.appspot.com',
    iosClientId:
        '25984849347-dk7vrm230a11f81gmvos3ti1evvk8jnv.apps.googleusercontent.com',
    iosBundleId: 'com.example.neoSgtUser',
  );
}
